import test from 'node:test';import assert from 'node:assert/strict';
import {OnlineTransport} from '../app/js/online-transport.mjs';
import {newInvite,channelKeys,seal,toBase64,bytesToMorse} from '../app/core/online-protocol.mjs';
import {packFastFrame} from '../app/core/fast-codec.mjs';
const opts={room:'0000',session:77,wpm:120,maxTurns:4,maxReplyBytes:180};
async function receiver(){const invite=newInvite('wss://example.com/v1',opts),events=[],a=new OnlineTransport({invite,sender:1});a.closed=false;a.hello=true;a.ready=true;a.material=await channelKeys(invite);a.nonce=toBase64(crypto.getRandomValues(new Uint8Array(16)));a.peerNonce=toBase64(crypto.getRandomValues(new Uint8Array(16)));a.received=0;a.onEvent=e=>events.push(e);return{a,invite,events};}
test('Authenticated packet is accepted once; encrypted replay rejected',async()=>{const {a,invite,events}=await receiver();try{const box=await seal(a.material.keys,invite,0,{t:'morse',from:a.peerNonce,to:a.nonce,n:1,m:bytesToMorse(packFastFrame({...opts,sender:0,seq:1,text:'はい'}))});await a.receive(box,0);assert.equal(events[0].frame.text,'はい');await assert.rejects(a.receive(box,0),/Replay/);assert.equal(events.length,1);}finally{a.stop();}});
for(const variant of ['to','from','n'])test('Peer session and counter binding rejects altered '+variant,async()=>{const {a,invite,events}=await receiver();try{const payload={t:'morse',from:a.peerNonce,to:a.nonce,n:1,m:bytesToMorse(packFastFrame({...opts,sender:0,seq:1,text:'はい'}))};payload[variant]=variant==='n'?2:'wrong';const box=await seal(a.material.keys,invite,0,payload);await assert.rejects(a.receive(box,0),/Replay/);assert.equal(events.length,0);}finally{a.stop();}});
test('Wrong frame sender is rejected even with valid AEAD tag',async()=>{const {a,invite}=await receiver();try{const box=await seal(a.material.keys,invite,0,{t:'morse',from:a.peerNonce,to:a.nonce,n:1,m:bytesToMorse(packFastFrame({...opts,sender:1,seq:2,text:'wrong'}))});await assert.rejects(a.receive(box,0),/Wrong sender/);}finally{a.stop();}});
test('Stop drops old-epoch valid data without delivery and is idempotent',async()=>{const {a,invite,events}=await receiver();const box=await seal(a.material.keys,invite,0,{t:'hello',nonce:a.peerNonce,pair:invite.p});a.stop();a.stop();await a.receive(box,0);assert.equal(events.length,0);assert.equal(a.material,null);});
test('Hello and proof must bind exact invite settings',async()=>{const {a,invite}=await receiver();try{a.ready=false;a.peerNonce=null;const box=await seal(a.material.keys,invite,0,{t:'hello',nonce:toBase64(crypto.getRandomValues(new Uint8Array(16))),pair:'MT2|0000|00000000|120|4|180'});await assert.rejects(a.receive(box,0),/settings/);}finally{a.stop();}});
test('Cancellation during pre-socket key derivation never opens a socket',async()=>{let calls=0;const a=new OnlineTransport({invite:newInvite('wss://example.com/v1',opts),sender:0,WebSocketClass:class{constructor(){calls++;}}});const p=a.start(()=>{});a.stop();await assert.rejects(p,/停止/);assert.equal(calls,0);});
