#!/usr/bin/env python3
"""Loopback demo monitor for MorseTalk.

Serves monitor/ (the visualisation page) and the real codec modules from app/core,
receives telemetry from endpoints on ws://127.0.0.1:PORT/feed, and broadcasts it to
viewers on ws://127.0.0.1:PORT/view. Viewers can ask the optional local Gemma 4 E2B
(OpenAI-compatible endpoint, default LM Studio on 127.0.0.1:1234) for readings and a
sentence guess; the request is forwarded as-is and never leaves the machine unless the
operator points E2B_URL elsewhere. No audio, no cloud, no listener outside loopback.
"""
from __future__ import annotations
import argparse, asyncio, json, mimetypes, os, re, sys, time, urllib.request
from collections import deque
from http import HTTPStatus
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MONITOR = ROOT / 'monitor'
E2B_URL = os.environ.get('E2B_URL', 'http://127.0.0.1:1234/v1/chat/completions')
E2B_MODEL = os.environ.get('E2B_MODEL', 'gemma-4-e2b-it')
STATIC_ROOTS = {'/': MONITOR, '/monitor/': MONITOR, '/app/core/': ROOT / 'app' / 'core'}
E2B_SYSTEM = (
    'あなたは日本語の読み仮名とローマ字を付ける係です。入力は途中まで受信した文章です。'
    '必ずJSONだけを返します。キー: hiragana（入力全体のひらがな読み。記号はそのまま）, '
    'romaji（同じ読みをヘボン式ローマ字で）, guess（この文がこの後どう続くかの予想を、入力を含めた完全な一文で。20文字以内の追加に留める）。'
    '入力に無い内容を hiragana / romaji に足さないこと。'
)
E2B_SCHEMA = {'type': 'object', 'properties': {'hiragana': {'type': 'string'}, 'romaji': {'type': 'string'}, 'guess': {'type': 'string'}},
              'required': ['hiragana', 'romaji', 'guess'], 'additionalProperties': False}


class Hub:
    def __init__(self, history=600):
        self.viewers: set = set()
        self.feeds: set = set()
        self.history: deque = deque(maxlen=history)
        self.e2b_ok = None
        self.e2b_latency = None

    async def broadcast(self, text: str):
        self.history.append(text)
        dead = []
        for ws in list(self.viewers):
            try:
                await ws.send(text)
            except Exception:
                dead.append(ws)
        for ws in dead:
            self.viewers.discard(ws)

    def e2b_call(self, text: str) -> dict:
        body = {'model': E2B_MODEL, 'temperature': 0, 'max_tokens': 200,
                'messages': [{'role': 'system', 'content': E2B_SYSTEM}, {'role': 'user', 'content': text}],
                'response_format': {'type': 'json_schema', 'json_schema': {'name': 'reading', 'strict': True, 'schema': E2B_SCHEMA}}}
        req = urllib.request.Request(E2B_URL, data=json.dumps(body).encode('utf-8'), headers={'Content-Type': 'application/json'})
        started = time.monotonic()
        with urllib.request.urlopen(req, timeout=60) as r:
            data = json.loads(r.read(1 << 20))
        content = data['choices'][0]['message']['content']
        m = re.search(r'\{.*\}', content, re.S)
        parsed = json.loads(m.group(0)) if m else {}
        self.e2b_latency = round((time.monotonic() - started) * 1000)
        self.e2b_ok = True
        return {'hiragana': str(parsed.get('hiragana', '')), 'romaji': str(parsed.get('romaji', '')), 'guess': str(parsed.get('guess', '')),
                'latencyMs': self.e2b_latency, 'model': data.get('model', E2B_MODEL), 'usage': data.get('usage')}

    async def viewer(self, ws):
        self.viewers.add(ws)
        try:
            await ws.send(json.dumps({'kind': 'monitor', 't': int(time.time() * 1000), 'feeds': len(self.feeds), 'e2b': self.e2b_ok, 'e2bModel': E2B_MODEL, 'history': list(self.history)}))
            async for raw in ws:
                if not isinstance(raw, str) or len(raw) > 4000:
                    continue
                try:
                    msg = json.loads(raw)
                except ValueError:
                    continue
                if msg.get('kind') == 'e2b' and isinstance(msg.get('text'), str) and 0 < len(msg['text']) <= 600:
                    rid = msg.get('id')
                    try:
                        result = await asyncio.get_running_loop().run_in_executor(None, self.e2b_call, msg['text'])
                        await ws.send(json.dumps({'kind': 'e2b-result', 'id': rid, 'text': msg['text'], **result}))
                    except Exception as exc:  # local model unavailable: the page falls back to its own kana table
                        self.e2b_ok = False
                        await ws.send(json.dumps({'kind': 'e2b-result', 'id': rid, 'text': msg['text'], 'error': type(exc).__name__}))
                elif msg.get('kind') == 'inject' and isinstance(msg.get('event'), dict):
                    # Demo replay generated by the page itself is echoed to every viewer.
                    event = msg['event']; event['t'] = int(time.time() * 1000); event['demo'] = True
                    await self.broadcast(json.dumps(event))
        finally:
            self.viewers.discard(ws)

    async def feed(self, ws):
        self.feeds.add(ws)
        try:
            await self.broadcast(json.dumps({'kind': 'feed-open', 't': int(time.time() * 1000), 'feeds': len(self.feeds)}))
            async for raw in ws:
                if isinstance(raw, str) and len(raw) <= 20000:
                    try:
                        json.loads(raw)
                    except ValueError:
                        continue
                    await self.broadcast(raw)
        finally:
            self.feeds.discard(ws)
            await self.broadcast(json.dumps({'kind': 'feed-close', 't': int(time.time() * 1000), 'feeds': len(self.feeds)}))

    async def handler(self, ws):
        path = ws.request.path
        if path == '/feed':
            await self.feed(ws)
        elif path == '/view':
            await self.viewer(ws)
        else:
            await ws.close(1008, 'unknown path')


def static_response(connection, request):
    from websockets.http11 import Response
    from websockets.datastructures import Headers
    path = request.path.split('?', 1)[0]
    if path in ('/feed', '/view'):
        return None
    if path == '/':
        path = '/monitor/index.html'
    for prefix, root in STATIC_ROOTS.items():
        if prefix != '/' and path.startswith(prefix):
            rel = path[len(prefix):]
            if not re.fullmatch(r'[A-Za-z0-9_.-]+(/[A-Za-z0-9_.-]+)*', rel) or '..' in rel:
                break
            target = (root / rel).resolve()
            if root.resolve() in target.parents and target.is_file():
                ctype = mimetypes.guess_type(str(target))[0] or 'application/octet-stream'
                if target.suffix == '.mjs':
                    ctype = 'text/javascript'
                body = target.read_bytes()
                return Response(200, 'OK', Headers([('Content-Type', f'{ctype}; charset=utf-8' if ctype.startswith('text') else ctype),
                                                    ('Content-Length', str(len(body))), ('Cache-Control', 'no-store')]), body)
            break
    body = b'Not found\n'
    return Response(404, 'Not Found', Headers([('Content-Type', 'text/plain'), ('Content-Length', str(len(body)))]), body)


async def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--port', type=int, default=8790)
    parser.add_argument('--no-browser', action='store_true')
    args = parser.parse_args(argv)
    from websockets.asyncio.server import serve
    hub = Hub()
    async with serve(hub.handler, '127.0.0.1', args.port, process_request=static_response, max_size=1 << 20, compression=None) as server:
        print(f'監視画面: http://127.0.0.1:{args.port}/', flush=True)
        print(f'端末側の監視先: ws://127.0.0.1:{args.port}/feed（adb reverse tcp:{args.port} tcp:{args.port} が必要）', flush=True)
        print(f'E2B: {E2B_URL} model={E2B_MODEL}（無ければ内蔵かな表で表示）', flush=True)
        if not args.no_browser:
            import webbrowser
            webbrowser.open(f'http://127.0.0.1:{args.port}/')
        await server.serve_forever()
    return 0


if __name__ == '__main__':
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        pass
